[package]
name = "the-interner"
version = "0.1.0"
edition = "2024"

[dependencies]
bumpalo = "3.17.0"
dashmap = { version = "7.0.0-rc2", features = ["raw-api", "inline-more"] }
hashbrown = { version = "0.15", default-features = false }
